# Generated by Django 6.0.6 on 2026-06-11 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Muqova rasmi')),
                ('tag', models.CharField(max_length=100, verbose_name='Teg (Food & Health, Recipes...)')),
                ('author', models.CharField(max_length=200, verbose_name='Muallif ismi')),
                ('content', models.TextField(verbose_name='Maqola matni')),
                ('comments', models.PositiveIntegerField(default=0, verbose_name='Izohlar soni')),
                ('is_active', models.BooleanField(default=True, verbose_name="Saytda ko'rsatilsinmi?")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog post',
                'verbose_name_plural': 'Blog postlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (URL uchun)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="To'liq ismi")),
                ('role', models.CharField(max_length=100, verbose_name='Lavozimi (Head Chef, Grill Master...)')),
                ('experience', models.PositiveIntegerField(verbose_name='Tajriba (yil)')),
                ('photo', models.ImageField(upload_to='chefs/', verbose_name='Foto')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Oshpaz',
                'verbose_name_plural': 'Oshpazlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('subject', models.CharField(choices=[('general', 'Umumiy savol'), ('catering', 'Catering va tadbirlar'), ('feedback', 'Fikr-mulohaza'), ('partnership', 'Hamkorlik'), ('media', 'Media va matbuot')], max_length=20, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilganmi?")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email manzil')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Obunachi',
                'verbose_name_plural': 'Obunachlar',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ism-Familiya')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('email', models.EmailField(max_length=254, verbose_name='Email manzil')),
                ('guests', models.CharField(choices=[('1', '1 kishi'), ('2', '2 kishi'), ('3-4', '3-4 kishi'), ('5-6', '5-6 kishi'), ('7-10', '7-10 kishi'), ('10+', '10+ kishi')], max_length=10, verbose_name='Mehmonlar soni')),
                ('date', models.DateField(verbose_name='Bron sanasi')),
                ('time', models.TimeField(verbose_name='Bron vaqti')),
                ('special_requests', models.TextField(blank=True, verbose_name="Maxsus so'rovlar")),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Tasdiqlangan?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bron',
                'verbose_name_plural': 'Bronlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
                ('role', models.CharField(max_length=100, verbose_name='Kim (Regular Customer, Food Blogger...)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonial/', verbose_name='Foto')),
                ('text', models.TextField(verbose_name='Sharh matni')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Yulduzlar (1-5)')),
                ('is_active', models.BooleanField(default=True, verbose_name="Saytda ko'rsatilsinmi?")),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Taom nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Narx ($)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Eski narx ($)')),
                ('image', models.ImageField(upload_to='menu/', verbose_name='Rasm')),
                ('badge', models.CharField(choices=[('hot', '🔥 Hot'), ('new', '✨ New'), ('bestseller', '⭐ Best Seller'), ('chefs_pick', "👨\u200d🍳 Chef's Pick"), ('none', "Yo'q")], default='none', max_length=20, verbose_name='Belgi (badge)')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Reyting (1-5)')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='Sharhlar soni')),
                ('calories', models.PositiveIntegerField(default=0, verbose_name='Kaloriya')),
                ('prep_time', models.PositiveIntegerField(default=15, verbose_name='Tayyorlash vaqti (daqiqa)')),
                ('tags', models.CharField(blank=True, max_length=300, verbose_name='Teglar (vergul bilan, masalan: Spicy,Bestseller)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjudmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Menyu elementi',
                'verbose_name_plural': 'Menyu elementlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
