# Generated by Django 5.2 on 2026-06-17 07:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Savat',
                'verbose_name_plural': 'Savatlar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Qabul qiluvchi ismi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('address', models.TextField(verbose_name='Yetkazib berish manzili')),
                ('comment', models.TextField(blank=True, verbose_name='Buyurtmaga izoh')),
                ('payment_method', models.CharField(choices=[('cash', '💵 Naqd pul (yetkazib berganda)'), ('card', '💳 Karta orqali (Payme / Click)')], default='cash', max_length=10, verbose_name="To'lov usuli")),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy narx ($)')),
                ('status', models.CharField(choices=[('new', '🆕 Yangi'), ('confirmed', '✅ Qabul qilindi'), ('preparing', '👨\u200d🍳 Tayyorlanmoqda'), ('on_the_way', "🚗 Yo'lda"), ('delivered', '📦 Yetkazildi'), ('cancelled', '❌ Bekor qilindi')], default='new', max_length=20, verbose_name='Buyurtma holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="Oxirgi o'zgarish")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='Taom nomi (buyurtma vaqtida)')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Narx (buyurtma vaqtida)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miqdor')),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.menuitem', verbose_name='Taom')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Buyurtma elementi',
                'verbose_name_plural': 'Buyurtma elementlari',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami')),
                ('address', models.TextField(blank=True, verbose_name='Doimiy manzil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profillar',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Miqdor')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart', verbose_name='Savat')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.menuitem', verbose_name='Taom')),
            ],
            options={
                'verbose_name': 'Savat elementi',
                'verbose_name_plural': 'Savat elementlari',
                'unique_together': {('cart', 'menu_item')},
            },
        ),
    ]
